#!/usr/bin/env python
# -*- encoding: utf-8; py-indent-offset: 4 -*-
# +------------------------------------------------------------------+
# |             ____ _               _        __  __ _  __           |
# |            / ___| |__   ___  ___| | __   |  \/  | |/ /           |
# |           | |   | '_ \ / _ \/ __| |/ /   | |\/| | ' /            |
# |           | |___| | | |  __/ (__|   <    | |  | | . \            |
# |            \____|_| |_|\___|\___|_|\_\___|_|  |_|_|\_\           |
# |                                                                  |
# | Copyright Mathias Kettner 2018             mk@mathias-kettner.de |
# +------------------------------------------------------------------+
#
# This file is part of Check_MK.
# The official homepage is at http://mathias-kettner.de/check_mk.
#
# check_mk is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  check_mk is  distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# tails. You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.


# example output


def inventory_speedtest(info):
    if info:
        for line in info[1:]:
            yield (line[0], {})


def check_speedtest(_item, _params, info):
    for line in info[1:]:
        server_id, server_sponsor, server_name, _timestamp, distance, ping, download, upload, sharelink, _address = line
        perfdata = []

        state = 0
        for what, textvalue, perftext, perfvalue in [
                ( 'Download rate', '%s' % get_nic_speed_human_readable(float(download)), 'download', float(download) ),
                ( 'Upload rate', '%s' % get_nic_speed_human_readable(float(upload)), 'upload', float(upload) ),
                ( 'Ping RTT', '%.2f ms' % float(ping), 'ping', float(ping) ),
                ( 'Server Distance', '%.2f km' % float(distance), 'distance', float(distance) )]:
            yield state, "%s: %s" % (what, textvalue), [(perftext, perfvalue)]

        yield 0, "Server: %s (ID %s, sponsored by %s)" % (server_name, server_id, server_sponsor)
        yield 0, "Graphic: %s" % sharelink


check_info['speedtest'] = {
    'inventory_function'    : inventory_speedtest,
    'check_function'        : check_speedtest,
    'has_perfdata'          : True,
    'service_description'   : 'Speedtest',
}
